# Joining Data with pandas

In [6]:
import os
os.getcwd()

'/Users/timmrahrt/Desktop/Handbook/Data_Science_Handbook/Data_Manipulation'

In [73]:
import pandas as pd
import numpy as np
import pickle
census = pd.read_csv("../ZDatasets/Chicago_census.csv")
wards = pd.read_csv("../ZDatasets/Chicago_wards.csv")
# Load the pickle file licenses
with open("../ZDatasets/licenses.p", "rb") as f:
    licenses = pickle.load(f) # could also use pd.read_pickle
# Correct the ward column to an integer
licenses['ward'] = licenses['ward'].astype('int64')
movies_to_genres = pd.read_pickle('../ZDatasets/movie_to_genres.p')

## 1. Data Merging Basics

### 1.1 Inner Join
Keeps only the rows where the value of 'ward' exists in both DataFrames.

In [29]:
wards_census = wards.merge(census, on = 'ward', suffixes=("_ward","_cen"))
wards_census.head()

,Unnamed: 0_ward,ward,alderman,address_ward,zip_ward,Unnamed: 0_cen,pop_2000,pop_2010,change,address_cen,zip_cen
0,1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,1,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
1,2,3,Pat Dowell,5046 SOUTH STATE STREET,60609,2,40385,53039,31%,17 EAST 38TH STREET,60653
2,3,4,William D. Burns,"435 EAST 35TH STREET, 1ST FLOOR",60616,3,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
3,4,5,Leslie A. Hairston,2325 EAST 71ST STREET,60649,4,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637
4,5,6,Roderick T. Sawyer,8001 S. MARTIN LUTHER KING DRIVE,60619,5,54989,52341,-5%,150 WEST 74TH STREET,60636

### 1.2 One to many relationships
Every row in the left table is related to only one row in the right table.

### 1.3 One to many relationships
Every row in the left table is related to one or more rows in the right table.

In [41]:
# Example
ward_licenses = wards.merge(licenses, on = 'ward', suffixes = ('_ward','_lic'))
print(wards.shape)
print(ward_licenses.shape)

(50, 5)
(9747, 10)

In [45]:
### 1.4 Merging multiple tables
wards.merge(licenses, on = 'ward', suffixes=("_wards","_lic")).merge(census, on='ward', suffixes = ("_wards","_census")).head()

,Unnamed: 0_wards,ward,alderman,address_wards,zip_wards,account,aid,business,address_lic,zip_lic,Unnamed: 0_census,pop_2000,pop_2010,change,address,zip
0,1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,10213,NaN,HOG HEAD MCDUNNA'S,1503-1507 W FULLERTON AVE 1ST,60614,1,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
1,1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,106,638,ZAVEN INC,260 E CHESTNUT ST 1ST,60611,1,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,10767,NaN,CAHG,211 E CHICAGO AVE 1600,60611,1,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
3,1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,11474,784,THE FRONTIER,1072 N MILWAUKEE AVE,60642,1,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
4,1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,12870,NaN,DAY BY DAY CALENDAR CO. # 4223,835 N MICHIGAN AVE 4 5071,60611,1,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622

## 2. Merging Tables with Different Join Types

### 2.1 Left join
Keeps all the rows from the left DataFrame, and only the matching rows from the right DataFrame.

In [53]:
# Get the data
movies = pd.read_pickle("../ZDatasets/movies.p")
taglines = pd.read_pickle("../ZDatasets/taglines.p")

In [55]:
# Merge with left join
movies_taglines = movies.merge(taglines, on = 'id', how = 'left')
movies_taglines.head()

,id,title,popularity,release_date,tagline
0,257,Oliver Twist,20.415572,2005-09-23,NaN
1,14290,Better Luck Tomorrow,3.877036,2002-01-12,Never underestimate an overachiever.
2,38365,Grown Ups,38.864027,2010-06-24,Boys will be boys. . . some longer than others.
3,9672,Infamous,3.680896,2006-11-16,There's more to the story than you know
4,12819,Alpha and Omega,12.300789,2010-09-17,A Pawsome 3D Adventure

### 2.2 Right join
Keeps all the rows from the right DataFrame, and only the matching rows from the left DataFrame.

In [57]:
movies_taglines_rj = movies.merge(taglines, on = 'id', how = 'right')
movies_taglines_rj.head()

,id,title,popularity,release_date,tagline
0,19995,Avatar,150.437577,2009-12-10,Enter the World of Pandora.
1,285,Pirates of the Caribbean: At World's End,139.082615,2007-05-19,"At the end of the world, the adventure begins."
2,206647,Spectre,107.376788,2015-10-26,A Plan No One Escapes
3,49026,The Dark Knight Rises,112.312950,2012-07-16,The Legend Ends
4,49529,John Carter,43.926995,2012-03-07,"Lost in our world, found in another."

### 2.3 Outer join
Keeps all rows from all tables. Will use 'NaN' for missing values.

In [58]:
movies_taglines_oj = movies.merge(taglines, on = 'id', how = 'outer')
movies_taglines_oj.head()

,id,title,popularity,release_date,tagline
0,5,Four Rooms,22.876230,1995-12-09,Twelve outrageous guests. Four scandalous requ...
1,11,Star Wars,126.393695,1977-05-25,"A long time ago in a galaxy far, far away..."
2,12,Finding Nemo,85.688789,2003-05-30,"There are 3.7 trillion fish in the ocean, they..."
3,13,Forrest Gump,138.133331,1994-07-06,"The world will never be the same, once you've ..."
4,14,American Beauty,80.878605,1999-09-15,Look closer.

### 2.4 Self join
Merging a table to itself.

In [63]:
# Get the data
sequels = pd.read_pickle("../ZDatasets/sequels.p")

In [64]:
original_sequels = sequels.merge(sequels, left_on = 'sequel', right_on = 'id', suffixes = ('_org','_seq'))
original_sequels.head()

,id_org,title_org,sequel_org,id_seq,title_seq,sequel_seq
0,862,Toy Story,863,863,Toy Story 2,10193
1,863,Toy Story 2,10193,10193,Toy Story 3,<NA>
2,675,Harry Potter and the Order of the Phoenix,767,767,Harry Potter and the Half-Blood Prince,<NA>
3,121,The Lord of the Rings: The Two Towers,122,122,The Lord of the Rings: The Return of the King,<NA>
4,120,The Lord of the Rings: The Fellowship of the Ring,121,121,The Lord of the Rings: The Two Towers,122

In [70]:
# Show sequels
original_sequels.loc[:,['title_org','title_seq']].head()

,title_org,title_seq
0,Toy Story,Toy Story 2
1,Toy Story 2,Toy Story 3
2,Harry Potter and the Order of the Phoenix,Harry Potter and the Half-Blood Prince
3,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Return of the King
4,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Two Towers

### 2.5 Index merge

In [77]:
movies_genres = movies.merge(movies_to_genres, left_on = "id", right_on = "movie_id")
movies_genres.head()

      id                 title  popularity release_date  movie_id   genre
0    257          Oliver Twist   20.415572   2005-09-23       257   Crime
1    257          Oliver Twist   20.415572   2005-09-23       257   Drama
2    257          Oliver Twist   20.415572   2005-09-23       257  Family
3  14290  Better Luck Tomorrow    3.877036   2002-01-12     14290   Crime
4  14290  Better Luck Tomorrow    3.877036   2002-01-12     14290   Drama

## 3. Advanced Merging and Concatenating

### 3.1 Filtering joins
- Mutating joins: Combines data from two tables based on matching observations in both tables.
- Filtering joins: Filter observations from table based on whether or not they match an observation in another table.

### 3.2 Semi joins
Returns the intersection, only columns from the left table and not the right. Doesn't return duplicates.

In [47]:
## 4. Merging Ordered and Time-Series Data