In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import iqr
student_alc = pd.read_csv("../ZDatasets/student-alcohol-consumption.csv", index_col=0)

# Explanatory Data Analysis

In [22]:
# Inspect the dataset
student_alc.head()

,school,sex,age,famsize,Pstatus,Medu,Fedu,traveltime,failures,schoolsup,...,goout,Dalc,Walc,health,absences,G1,G2,G3,location,study_time
0,GP,F,18,GT3,A,4,4,2,0,yes,...,4,1,1,3,6,5,6,6,Urban,2 to 5 hours
1,GP,F,17,GT3,T,1,1,1,0,no,...,3,1,1,3,4,5,5,6,Urban,2 to 5 hours
2,GP,F,15,LE3,T,1,1,1,3,yes,...,2,2,3,3,10,7,8,10,Urban,2 to 5 hours
3,GP,F,15,GT3,T,4,2,1,0,no,...,2,1,1,5,2,15,14,15,Urban,5 to 10 hours
4,GP,F,16,GT3,T,3,3,1,0,no,...,2,1,2,5,4,6,10,10,Urban,2 to 5 hours

## 1. Finding outliers

We subset the column for values under the data - 1.5 * iqr and above the data + 1.5 * iqr threshold.

In [23]:
iqr = iqr(student_alc['age'])
lower_threshold = np.quantile(student_alc['age'], 0.25) - 1.5 * iqr
upper_threshold = np.quantile(student_alc['age'], 0.75) + 1.5 * iqr
student_alc[(student_alc['age'] < lower_threshold) | (student_alc['age'] > upper_threshold)]

# Alternatively: student['age'].describe()

,school,sex,age,famsize,Pstatus,Medu,Fedu,traveltime,failures,schoolsup,...,goout,Dalc,Walc,health,absences,G1,G2,G3,location,study_time
247,GP,M,22,GT3,T,3,1,1,3,no,...,5,5,5,1,16,6,8,8,Urban,<2 hours